### PR TITLE
tests: Ensure removed SDFormat elements raise errors in newer versions

### LINKED ISSUE #327: `//joint/axis/use_parent_model_frame` does not fail fast or issue a warning in SDFormat 1.7?
Ran across this here:
https://github.com/robotlocomotion/drake/pull/13758#pullrequestreview-459542067

Specifically, here:
https://github.com/RobotLocomotion/drake/blob/ab20bf25d9e9c05f861d7b6905cd6ef4dd9950c7/examples/multibody/four_bar/four_bar.sdf#L249
(note that `//sdf/@version="1.7"`)

Perhaps it did print out a console warning... will need to confirm.
Ideally, though, this would eventually cause things to fail fast. Perhaps in SDFormat 1.8, we can make custom elements much more strict? (e.g. it *must* be namespaced?)

FYI @scpeters @azeey

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #327 (explicitly)
Follow-up to #481

Uses model setup from issue:
https://github.com/RobotLocomotion/drake/blob/ab20bf25d9e9c05f861d7b6905cd6ef4dd9950c7/examples/multibody/four_bar/four_bar.sdf#L249

\cc @brawner

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
FWIW Tested locally with following setup:
https://github.com/EricCousineau-TRI/repro/blob/d09ae01a4cd0aef962b671f90c03a265e0eef979/ros/sdformat_workspace/README.md

**Review by brawner — APPROVED** [review]
Nice, looks good to me.

File: test/integration/unknown.cc [hunk 1]
```diff
@@ -135,3 +135,54 @@ TEST(UnrecognizedElements, UnrecognizedElementsWithNamespaces)
...
+
+/////////////////////////////////////////////////
+/// Test that elements that aren't part of the version of the spec
+/// cause an error (#327) - e.g. something that was valid in SDFormat 1.6 but
+/// not in SDFormat>=1.7 (https://git.io/JtKKb).
+TEST(UnrecognizedElements, OldElementsInNewSchemas)
+{
+  // This should be valid in 1.6, but not in 1.8 (do to usage of
+  // `use_parent_model_frame`).
+  auto make_model_xml_string = [](std::string version) {
```
Comment (scpeters) [inline test/integration/unknown.cc:147]: nit: our codecheck doesn't like the `{` on the same line

Comment (EricCousineau-TRI) [reply test/integration/unknown.cc]: Done. Oops!

**Review by jennuine — APPROVED** [review]
LGTM!

**Review by scpeters — APPROVED** [review]

**Comment by brawner** [comment]
@EricCousineau-TRI Do you have merge privileges on this repo, or do you need someone to merge for you?

**Comment by EricCousineau-TRI** [comment]
Nope, no merge privileges (and it's good that I don't have 'em :P) - can you merge it?
